const employees = [
  {
    id: "emp001",
    firstName: "Amit",
    email: "e@e.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 2,
      completed: 5,
      failed: 2,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Update Client Database",
        taskDescription: "Clean and update the client records in the CRM.",
        taskDate: "2025-06-01",
        category: "Database",
        priority: "low",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Send Weekly Report",
        taskDescription: "Compile and send the weekly performance report.",
        taskDate: "2025-05-29",
        category: "Reporting",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Conduct Interview",
        taskDescription: "Interview frontend developer candidates.",
        taskDate: "2025-05-25",
        category: "HR",
        priority: "medium",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Backup Databases",
        taskDescription: "Manually backup production and dev DBs.",
        taskDate: "2025-06-01",
        category: "IT",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "System Health Check",
        taskDescription: "Run diagnostics on all backend systems.",
        taskDate: "2025-05-30",
        category: "Maintenance",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review Finance Docs",
        taskDescription: "Approve Q2 financial documentation.",
        taskDate: "2025-05-27",
        category: "Finance",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Client Demo",
        taskDescription: "Failed to present demo due to connectivity.",
        taskDate: "2025-05-28",
        category: "Client",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Server Migration",
        taskDescription: "Unsuccessful migration of legacy server.",
        taskDate: "2025-05-26",
        category: "IT",
        priority: "low",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Add Two-Factor Auth",
        taskDescription: "Implement 2FA in login system.",
        taskDate: "2025-06-02",
        category: "Security",
        priority: "low",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Setup Git Hooks",
        taskDescription: "Add pre-commit and pre-push hooks.",
        taskDate: "2025-05-30",
        category: "DevOps",
        priority: "high",
      },
    ],
  },
  {
    id: "emp002",
    firstName: "Priya",
    email: "emp002@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 4,
      failed: 3,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Dashboard UI",
        taskDescription: "Create Figma designs for the analytics dashboard.",
        taskDate: "2025-06-02",
        category: "Design",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Team Standup",
        taskDescription: "Attend and report daily team progress.",
        taskDate: "2025-06-01",
        category: "Meetings",
        priority: "low",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Push Code to Git",
        taskDescription: "Commit and push latest changes to GitHub repo.",
        taskDate: "2025-05-30",
        category: "Development",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Onboard New Intern",
        taskDescription: "Complete onboarding checklist for the new intern.",
        taskDate: "2025-05-29",
        category: "HR",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Client Presentation",
        taskDescription:
          "Missed the client presentation due to network issues.",
        taskDate: "2025-05-29",
        category: "Client",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Integration Testing",
        taskDescription: "Failed due to API mismatch.",
        taskDate: "2025-05-27",
        category: "Testing",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Cloud Sync",
        taskDescription: "Data not syncing with AWS S3.",
        taskDate: "2025-05-26",
        category: "Cloud",
        priority: "medium",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "UI Accessibility Review",
        taskDescription: "Audit for screen reader and tab navigation.",
        taskDate: "2025-06-02",
        category: "UX",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Internal Newsletter",
        taskDescription: "Write and distribute monthly newsletter.",
        taskDate: "2025-05-25",
        category: "Communication",
        priority: "low",
      },
    ],
  },
  {
    id: "emp003",
    firstName: "Ravi",
    email: "emp003@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 3,
      failed: 2,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Database Optimization",
        taskDescription:
          "Improve query performance for the analytics database.",
        taskDate: "2025-06-01",
        category: "Database",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Code Review",
        taskDescription: "Review pull requests for the user auth module.",
        taskDate: "2025-05-31",
        category: "Code Review",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Script Automation",
        taskDescription: "Automate deployment scripts.",
        taskDate: "2025-05-30",
        category: "DevOps",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Login Token Bug",
        taskDescription: "Session expiration not triggering re-login.",
        taskDate: "2025-05-29",
        category: "Bug Fixing",
        priority: "high",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Upgrade NodeJS",
        taskDescription: "Upgrade backend from Node 14 to Node 18.",
        taskDate: "2025-06-02",
        category: "Development",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Clean Up Logs",
        taskDescription: "Archive logs older than 6 months.",
        taskDate: "2025-05-28",
        category: "Maintenance",
        priority: "low",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "OAuth Integration",
        taskDescription: "Failed to validate user scopes from Google login.",
        taskDate: "2025-05-27",
        category: "Integration",
        priority: "high",
      },
    ],
  },
  {
    id: "emp004",
    firstName: "Sneha",
    email: "emp004@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 4,
      failed: 2,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Write Unit Tests",
        taskDescription: "Write unit tests for the new billing module.",
        taskDate: "2025-06-02",
        category: "Testing",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Deploy to Staging",
        taskDescription: "Deploy the latest features to the staging server.",
        taskDate: "2025-05-31",
        category: "DevOps",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "API Integration",
        taskDescription: "Failed to connect with the 3rd-party API provider.",
        taskDate: "2025-05-30",
        category: "Integration",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Write User Docs",
        taskDescription: "Document features for the end-user portal.",
        taskDate: "2025-05-29",
        category: "Documentation",
        priority: "medium",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Refactor Billing Logic",
        taskDescription: "Simplify and modularize the billing service.",
        taskDate: "2025-06-02",
        category: "Development",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Accessibility Test",
        taskDescription: "Run a11y tests on all key pages.",
        taskDate: "2025-05-27",
        category: "Testing",
        priority: "low",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Code Merge Conflict",
        taskDescription: "Failed to resolve merge conflict in checkout flow.",
        taskDate: "2025-05-26",
        category: "Code Review",
        priority: "high",
      },
    ],
  },
  {
    id: "emp005",
    firstName: "Kiran",
    email: "emp005@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 2,
      completed: 6,
      failed: 3,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Customer Feedback Analysis",
        taskDescription: "Analyze customer feedback from the last quarter.",
        taskDate: "2025-06-02",
        category: "Analysis",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Marketing Email Campaign",
        taskDescription: "Launch summer discount email campaign.",
        taskDate: "2025-05-30",
        category: "Marketing",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Survey Results Report",
        taskDescription: "Report was not delivered due to missing data.",
        taskDate: "2025-05-29",
        category: "Reporting",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "SEO Optimization",
        taskDescription: "Optimize website meta tags and URLs for SEO.",
        taskDate: "2025-05-28",
        category: "SEO",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Social Media Plan",
        taskDescription: "Design 1-month content calendar.",
        taskDate: "2025-05-27",
        category: "Marketing",
        priority: "medium",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Ad Budget Proposal",
        taskDescription: "Prepare digital marketing ad budget.",
        taskDate: "2025-05-26",
        category: "Finance",
        priority: "low",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Email Delivery Error",
        taskDescription: "Marketing emails bounced for 30% users.",
        taskDate: "2025-05-25",
        category: "Marketing",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Customer Call Missed",
        taskDescription: "Client call missed due to incorrect scheduling.",
        taskDate: "2025-05-24",
        category: "Client",
        priority: "high",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Weekly Summary Post",
        taskDescription: "Post LinkedIn summary of weekly team wins.",
        taskDate: "2025-05-23",
        category: "Social Media",
        priority: "low",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Trend Analysis",
        taskDescription: "Analyze competitor trend from SEMRush.",
        taskDate: "2025-06-02",
        category: "SEO",
        priority: "high",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Improve Landing Page",
        taskDescription: "A/B test new layout design.",
        taskDate: "2025-06-02",
        category: "Design",
        priority: "medium",
      },
    ],
  },
];

const admin = [
  {
    id: "admin001",
    firstName: "Mohit",
    email: "admin@p.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
 